name: vfm_3wdataset
channels:
  - defaults
  - conda-forge
  - pyzo
  - anaconda
dependencies:
  - click
  - coverage
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - notebook
  - numpy
  - pandas
  - pint
  - pip
  - psutil
  - pycryptodomex
  - pylint
  - pyppmd
  - pytest
  - python=3.9
  - pyzstd
  - scipy
  - pip:
    - catboost==1.2.3
    - dvc==3.38.1
    - dvc-s3==3.0.1
    - dvc-ssh==3.0.0
    - feature-engine==1.5.2
    - h5py
    - hydra-core
    - jupyterlab
    - kaleido
    - mlflow==2.14.2
    - minio==7.2.3
    - model-bakery
    - openpyxl==3.0.10
    - optuna==3.5.0
    - papermill==2.6.0
    - plotly==5.14.1
    - py7zr==0.20.2
    - python-dotenv==1.0.1
    - pyyaml
    - scikeras==0.8.0
    - scikit-learn
    - tensorflow==2.11.0
    - trino==0.327.0
    - xgboost==1.7.3
    - xlrd==2.0.1
